apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: vote-ui
  template:
    metadata:
      labels:
        app: vote-ui
    spec:
      containers:
      - image: docker.io/kzwolenik95/vote:bbaf04a19647b11c44156149320e45045e70562e
        name: vote-ui
        ports:
        - containerPort: 80